package execution.tkbl.site;

import common.cases.CommonScenarios;
import execution.BaseTest;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import talkable.site.homePage.TkblHomePage;
import util.EnvFactory;
import util.TestDataGenerator;

public class TalkableSiteFormsTesting extends BaseTest{

    //test data:
    private String firstName = "Auto" + TestDataGenerator.getRandomId();
    private String lastName = "AutomationLastName";
    private String company = "Talkable Automation Testing";
    private String email = "maxim.laba+automation@talkable.com";
    private String phone = "33333333333";
    private String question = "Request was generated by the Talkable automation script. Please ignore.";

    @BeforeMethod
    public void navigateToTalkableHomePage(){
        CommonScenarios.navigateToUrl(EnvFactory.getEnvUrl());
    }

    @Test
    public void contactUs(){
        CommonScenarios.openContactUsPage(new TkblHomePage());
        CommonScenarios.submitContactUsForm(firstName, lastName, company, email, phone, question);
    }

    @Test
    public void requestHandbook(){
        //todo:
    }

    @Test
    public void requestDemo(){
        //todo:
    }

    @Test
    public void requestPricing(){
        //todo:
    }

}
