package execution.tkbl.site;

import common.cases.CommonScenarios;
import execution.BaseTest;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import talkable.site.homePage.TkblHomePage;
import util.EnvFactory;
import util.TestDataGenerator;

public class TalkableSiteFormsTesting extends BaseTest{

    //test data:
    private String firstName = "Auto" + TestDataGenerator.getRandomId();
    private String lastName = "AutomationLastName";
    private String company = "Talkable Automation Testing";
    private String webSiteUrl = "www.automation.test.com";
    private String email = "maxim.laba+automation@talkable.com";
    private String phone = "33333333333";
    private String question = "Request was generated by the Talkable automation script. Please ignore.";
    private String averageMonthlyWebsiteViews = "Pre-launch";

    @BeforeClass
    public void setup(){
        CommonScenarios.acceptCookiesUsage();
    }

    @BeforeMethod
    public void navigateToTalkableHomePage(){
        CommonScenarios.navigateToUrl(EnvFactory.getEnvUrl());
    }

    @Test
    public void contactUs(){
        CommonScenarios.openContactUsPage(new TkblHomePage());
        CommonScenarios.submitContactUsForm(firstName, lastName, company, email, phone, question);
    }

    @Test
    public void requestHandbook(){
        CommonScenarios.openGetHandbookPage();
        CommonScenarios.submitGetBookForm(firstName, lastName, webSiteUrl, email, averageMonthlyWebsiteViews);
        Assert.assertEquals(
                CommonScenarios.getMessageHeaderFromDownloadHandBookPage(),
                "Thank You!",
                "Incorrect Message header on the Download Handbook page when Get Handbook form was submitted");
        Assert.assertEquals(
                CommonScenarios.getMessageTextFromDownloadHandBookPage(),
                "Download the handbook below:",
                "Incorrect Message text on the Download Handbook page when Get Handbook form was submitted");
    }

    @Test
    public void requestDemo(){
        //todo:
    }

    @Test
    public void requestPricing(){
        //todo:
    }

}
